import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box, Grid, GridItem } from '@chakra-ui/react'
import ContentBlock from '../components/ContentBlock'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Steve
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box layerStyle="page">
          <Grid
            templateRows={{ base: 'repeat(1, 1fr)', md: 'repeat(auto, 1fr)' }}
            templateColumns={{ base: 'repeat(1, 1fr)', md: 'repeat(4, 1fr)' }}
            columnGap={1}
            rowGap={1}
          >
            <GridItem rowSpan={1} colSpan={4}>
              <ContentBlock request={{ id: "75761646-16b9-4ccd-96bb-dbb1fac6393d" }} />
            </GridItem>
          </Grid>
        </Box>
      </main>
    </div>
  )
}
